version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "api"
s3_prefix = "api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "api-dev"
s3_prefix = "api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
