[project]
name = "notify-lambda"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "shared-db",
    "cryptography>=41.0.0",
    "jinja2>=3.1.2",
    "requests>=2.28.1",
]

[tool.uv.sources]
shared-db = { workspace = true }
